[package]
name = "arm"
version = "0.0.1"
authors = ["uvekilledkenny"]

[dependencies]
baselib = { path = "../baselib" }

[profile.release]
panic = "abort"
opt-level = 3
lto = true

[lib]
crate-type = ["staticlib"]