[package]
name = "thumb"
version = "0.0.1"
authors = ["uvekilledkenny"]

[profile.release]
panic = "abort"
opt-level = 3
lto = true

[lib]
name="thumb"
crate-type = ["staticlib"]

[dependencies]
baselib = { path = "../baselib" }